from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
from ml_engine import calculate_landslide_risk

app = FastAPI(
    title="LandGuard AI - Landslide Risk Intelligence Platform",
    description="Geotechnical AI & Early Warning Hazard Detection Platform",
    version="2.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class SensorData(BaseModel):
    rainfall_mm: float = Field(..., ge=0, le=500, description="24h cumulative rainfall in mm")
    soil_moisture_pct: float = Field(..., ge=0, le=100, description="Volumetric soil moisture percentage")
    slope_deg: float = Field(..., ge=0, le=90, description="Slope inclination angle in degrees")
    pore_pressure_kpa: Optional[float] = Field(None, ge=0, le=200, description="Pore-water pressure in kPa")
    vegetation_cover_pct: Optional[float] = Field(65.0, ge=0, le=100, description="NDVI vegetation index percentage")
    seismic_pga: Optional[float] = Field(0.05, ge=0, le=1.0, description="Peak Ground Acceleration in g")
    zone_id: Optional[str] = Field("zone-sikkim-1", description="Identifier of the monitored slope sector")


class ExportReportRequest(BaseModel):
    zone_name: str
    risk_pct: int
    risk_level: str
    factor_of_safety: float
    rainfall_mm: float
    soil_moisture_pct: float
    slope_deg: float
    operator_notes: Optional[str] = "Automated sensor telemetry report generated by LandGuard AI."


# Pre-configured high-risk geological monitoring zones across India
MONITORED_ZONES = [
    {
        "id": "zone-sikkim-1",
        "name": "Gangtok North Ridge",
        "state": "Sikkim",
        "lat": 27.3389,
        "lng": 88.6065,
        "elevation_m": 1650,
        "rainfall_mm": 158.0,
        "soil_moisture_pct": 82.0,
        "slope_deg": 38.0,
        "station_id": "ST-SKM-01",
        "status": "Online",
    },
    {
        "id": "zone-kerala-1",
        "name": "Wayanad Meppadi Slope",
        "state": "Kerala",
        "lat": 11.5534,
        "lng": 76.1264,
        "elevation_m": 920,
        "rainfall_mm": 195.0,
        "soil_moisture_pct": 88.0,
        "slope_deg": 42.0,
        "station_id": "ST-WND-04",
        "status": "Warning",
    },
    {
        "id": "zone-kerala-2",
        "name": "Munnar Gap Road",
        "state": "Kerala",
        "lat": 10.0889,
        "lng": 77.0595,
        "elevation_m": 1530,
        "rainfall_mm": 112.0,
        "soil_moisture_pct": 69.0,
        "slope_deg": 34.0,
        "station_id": "ST-MNR-02",
        "status": "Online",
    },
    {
        "id": "zone-uk-1",
        "name": "Joshimath Subsidence Belt",
        "state": "Uttarakhand",
        "lat": 30.5564,
        "lng": 79.5667,
        "elevation_m": 1890,
        "rainfall_mm": 84.0,
        "soil_moisture_pct": 61.0,
        "slope_deg": 46.0,
        "station_id": "ST-JSH-09",
        "status": "Online",
    },
    {
        "id": "zone-hp-1",
        "name": "Shimla Taradevi Corridor",
        "state": "Himachal Pradesh",
        "lat": 31.0783,
        "lng": 77.1472,
        "elevation_m": 2040,
        "rainfall_mm": 65.0,
        "soil_moisture_pct": 52.0,
        "slope_deg": 31.0,
        "station_id": "ST-SML-03",
        "status": "Online",
    },
    {
        "id": "zone-wb-1",
        "name": "Darjeeling Lebong Spur",
        "state": "West Bengal",
        "lat": 27.0600,
        "lng": 88.2600,
        "elevation_m": 2134,
        "rainfall_mm": 140.0,
        "soil_moisture_pct": 74.0,
        "slope_deg": 36.0,
        "station_id": "ST-DAR-07",
        "status": "Online",
    },
]


@app.get("/api/health")
def health_check():
    return {
        "status": "ok",
        "service": "LandGuard AI Geotechnical Engine",
        "version": "2.0.0",
        "model": "Landslide-FoS-Hydrological-v2",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "active_zones_count": len(MONITORED_ZONES),
    }


@app.post("/api/predict")
def predict_risk(data: SensorData):
    (
        risk_pct,
        risk_level,
        factor_of_safety,
        contributors,
        confidence,
        ai_summary,
        recommendation,
        chain_reaction,
        metrics,
    ) = calculate_landslide_risk(
        rainfall=data.rainfall_mm,
        soil_moisture=data.soil_moisture_pct,
        slope=data.slope_deg,
        pore_pressure=data.pore_pressure_kpa,
        vegetation_cover=data.vegetation_cover_pct,
        seismic_pga=data.seismic_pga,
    )

    return {
        "overall_risk_pct": risk_pct,
        "risk_level": risk_level,
        "factor_of_safety": factor_of_safety,
        "contributors": contributors,
        "confidence": confidence,
        "ai_summary": ai_summary,
        "recommendation": recommendation,
        "chain_reaction": chain_reaction,
        "metrics": metrics,
        "inputs": {
            "rainfall_mm": data.rainfall_mm,
            "soil_moisture_pct": data.soil_moisture_pct,
            "slope_deg": data.slope_deg,
            "pore_pressure_kpa": metrics.get("pore_pressure_kpa"),
            "vegetation_cover_pct": data.vegetation_cover_pct,
            "seismic_pga": data.seismic_pga,
        },
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


@app.get("/api/zones")
def get_monitored_zones():
    # Calculate live risk rating for each zone
    enhanced_zones = []
    for zone in MONITORED_ZONES:
        risk_score, risk_level, fos, _, conf, summary, _, chain, _ = calculate_landslide_risk(
            rainfall=zone["rainfall_mm"],
            soil_moisture=zone["soil_moisture_pct"],
            slope=zone["slope_deg"],
        )
        enhanced_zones.append({
            **zone,
            "risk_pct": risk_score,
            "risk_level": risk_level,
            "factor_of_safety": fos,
            "confidence": conf,
            "ai_summary": summary,
            "chain_reaction": chain,
        })
    return {"zones": enhanced_zones, "count": len(enhanced_zones)}


@app.get("/api/history")
def get_risk_history():
    return {
        "history": [
            {"time": "00:00", "rainfall": 24, "soil_moisture": 45, "slope": 36, "risk_pct": 18, "level": "LOW", "fos": 2.12},
            {"time": "03:00", "rainfall": 48, "soil_moisture": 52, "slope": 36, "risk_pct": 28, "level": "LOW", "fos": 1.95},
            {"time": "06:00", "rainfall": 86, "soil_moisture": 64, "slope": 36, "risk_pct": 46, "level": "MODERATE", "fos": 1.62},
            {"time": "09:00", "rainfall": 120, "soil_moisture": 74, "slope": 36, "risk_pct": 65, "level": "HIGH", "fos": 1.34},
            {"time": "12:00", "rainfall": 155, "soil_moisture": 84, "slope": 36, "risk_pct": 82, "level": "CRITICAL", "fos": 0.98},
            {"time": "15:00", "rainfall": 142, "soil_moisture": 78, "slope": 36, "risk_pct": 74, "level": "HIGH", "fos": 1.15},
            {"time": "Live", "rainfall": 142, "soil_moisture": 78, "slope": 36, "risk_pct": 74, "level": "HIGH", "fos": 1.15},
        ]
    }


@app.get("/api/alerts")
def get_alerts():
    return {
        "alerts": [
            {
                "id": "ALT-2026-089",
                "title": "Critical Pore-Water Surcharge Alert",
                "zone": "Wayanad Meppadi Slope",
                "severity": "CRITICAL",
                "risk_pct": 88,
                "timestamp": "12 min ago",
                "action": "Immediate traffic diversion & NDRF standby alert",
                "acknowledged": False
            },
            {
                "id": "ALT-2026-088",
                "title": "Sustained Monsoon Inflow Trigger",
                "zone": "Gangtok North Ridge",
                "severity": "HIGH",
                "risk_pct": 74,
                "timestamp": "34 min ago",
                "action": "Deploy UAV inspection squad to toe culverts",
                "acknowledged": True
            },
            {
                "id": "ALT-2026-087",
                "title": "Subsidence Micro-Seismic Watch",
                "zone": "Joshimath Subsidence Belt",
                "severity": "MODERATE",
                "risk_pct": 48,
                "timestamp": "1 hr ago",
                "action": "Calibrate laser extensometer lines",
                "acknowledged": True
            },
            {
                "id": "ALT-2026-086",
                "title": "Drainage Siltation Advisory",
                "zone": "Darjeeling Lebong Spur",
                "severity": "MODERATE",
                "risk_pct": 42,
                "timestamp": "2 hrs ago",
                "action": "Clear roadside culvert catchments",
                "acknowledged": False
            }
        ]
    }


@app.get("/api/stations")
def get_stations():
    return {
        "stations": [
            {
                "id": "ST-SKM-01",
                "name": "Gangtok Ridge Station Alpha",
                "zone": "Sikkim Eastern Slopes",
                "status": "Online",
                "signal_rssi": "-64 dBm (98%)",
                "battery_pct": 94,
                "solar_power_w": 48.2,
                "sensors": ["Piezometer", "Inclinometer", "Tipping Rain Gauge", "TDR Soil Probe"],
                "last_ping": "8 seconds ago",
            },
            {
                "id": "ST-WND-04",
                "name": "Wayanad Ghat Sensor Unit",
                "zone": "Meppadi Catchment",
                "status": "Warning",
                "signal_rssi": "-78 dBm (84%)",
                "battery_pct": 76,
                "solar_power_w": 22.1,
                "sensors": ["Acoustic Pore Sensor", "Inclinometer Array", "Rain Gauge"],
                "last_ping": "14 seconds ago",
            },
            {
                "id": "ST-MNR-02",
                "name": "Munnar Gap Telemetry Node",
                "zone": "High-Range Route 49",
                "status": "Online",
                "signal_rssi": "-68 dBm (92%)",
                "battery_pct": 89,
                "solar_power_w": 52.0,
                "sensors": ["Piezometer", "Crack Meter", "Soil Sensor"],
                "last_ping": "5 seconds ago",
            },
            {
                "id": "ST-JSH-09",
                "name": "Joshimath Laser Base Node",
                "zone": "Alaknanda Escarpment",
                "status": "Online",
                "signal_rssi": "-71 dBm (88%)",
                "battery_pct": 91,
                "solar_power_w": 44.5,
                "sensors": ["Laser Distance Meter", "Seismometer", "Moisture Probe"],
                "last_ping": "12 seconds ago",
            },
        ]
    }


@app.post("/api/export-report")
def export_hazard_report(data: ExportReportRequest):
    return {
        "report_id": f"LG-REP-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "zone_name": data.zone_name,
        "executive_summary": f"LandGuard AI hazard evaluation for {data.zone_name}. Evaluated risk index is {data.risk_pct}% ({data.risk_level}) with Factor of Safety {data.factor_of_safety}.",
        "telemetry_snapshot": {
            "rainfall_mm": data.rainfall_mm,
            "soil_moisture_pct": data.soil_moisture_pct,
            "slope_deg": data.slope_deg,
        },
        "status": "Official Disaster Management Dispatch Ready",
        "notes": data.operator_notes,
    }


if __name__ == "__main__":
    import uvicorn
    print("\n" + "=" * 55)
    print("  [OK] Starting LandGuard AI Backend Server")
    print("  API URL:  http://localhost:8000")
    print("  API Docs: http://localhost:8000/docs")
    print("=" * 55 + "\n")
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)